AWSTemplateFormatVersion: '2010-09-09'
Description: cfn API GW for upload & search

Resources:
  cfn-PhotoApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: cfn-PhotoAlbumAPI
      BinaryMediaTypes: ['image/png','image/jpg','image/jpeg','image/heic']

  cfn-UploadResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref cfn-PhotoApi
      ParentId: !GetAtt cfn-PhotoApi.RootResourceId
      PathPart: upload

  cfn-PutUploadMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref cfn-PhotoApi
      ResourceId: !Ref cfn-UploadResource
      HttpMethod: PUT
      AuthorizationType: NONE
      RequestParameters:
        method.request.querystring.filename:            true
        method.request.header.Content-Type:             true
        method.request.header.x-amz-meta-customLabels:  false
      Integration:
        Type: AWS
        IntegrationHttpMethod: PUT
        Uri: !Sub >
          arn:aws:apigateway:${AWS::Region}:s3:path/${cfn-PhotoAlbum-PhotoBucketName}/{objectKey}
        Credentials: !GetAtt cfn-ApiGatewayS3Role.Arn
        PassthroughBehavior: WHEN_NO_TEMPLATES
        RequestParameters:
          integration.request.path.objectKey:             'method.request.querystring.filename'
          integration.request.header.Content-Type:        'method.request.header.Content-Type'
          integration.request.header.x-amz-meta-customLabels: 'method.request.header.x-amz-meta-customLabels'

  cfn-OptionsUpload:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref cfn-PhotoApi
      ResourceId: !Ref cfn-UploadResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates: { 'application/json': '{ "statusCode": 200 }' }
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,x-amz-meta-customLabels'"
              method.response.header.Access-Control-Allow-Methods: "'PUT,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin:  "'*'"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin:  true

  cfn-SearchResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref cfn-PhotoApi
      ParentId: !GetAtt cfn-PhotoApi.RootResourceId
      PathPart: search

  cfn-GetSearch:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref cfn-PhotoApi
      ResourceId: !Ref cfn-SearchResource
      HttpMethod: GET
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub >
          arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${cfn-PhotoAlbum-SearchFunctionArn}/invocations

  cfn-OptionsSearch:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref cfn-PhotoApi
      ResourceId: !Ref cfn-SearchResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates: { 'application/json': '{ "statusCode": 200 }' }
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type'"
              method.response.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin:  "'*'"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin:  true

  cfn-PermissionSearchInvoke:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !ImportValue cfn-PhotoAlbum-SearchFunctionArn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${cfn-PhotoApi}/*/GET/search

Outputs:
  cfn-ApiUrl:
    Value: !Sub 'https://${cfn-PhotoApi}.execute-api.${AWS::Region}.amazonaws.com/prod'
    Export: { Name: cfn-PhotoAlbum-ApiUrl }

  cfn-ApiId:
    Value: !Ref cfn-PhotoApi
    Export: { Name: cfn-PhotoAlbum-ApiId }
