AWSTemplateFormatVersion: '2010-09-09'
Description: All global parameters for the Photo Album stack.

Parameters:
  ESDomainEndpoint:
    Type: String
    Description: "Your existing OpenSearch domain endpoint"
    Default: "https://search-photos-2kdopq4li5ts2w6mcaqobflreu.us-east-1.es.amazonaws.com"

  ESDomainArn:
    Type: String
    Description: "ARN of your existing OpenSearch domain, with /* suffix"
    Default: "arn:aws:es:us-east-1:825765411228:domain/photos/*"
