AWSTemplateFormatVersion: '2010-09-09'
Description: S3 buckets: photo storage & frontend hosting.

Parameters:
  PhotoBucketSuffix:
    Type: String
    Default: "my-photo-bucket-hw3"

  FrontendBucketSuffix:
    Type: String
    Default: "my-frontend-bucket-hw3"
    
Resources:
  cfn-PhotoStorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "cfn-${PhotoBucketSuffix}"
      VersioningConfiguration: { Status: Enabled }
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault: { SSEAlgorithm: AES256 }
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

  cfn-FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "cfn-${FrontendBucketSuffix}"
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument:  error.html
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault: { SSEAlgorithm: AES256 }
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: false
        RestrictPublicBuckets: false

  cfn-FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref cfn-FrontendBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub '${cfn-FrontendBucket}/*'

Outputs:
  cfn-PhotoBucketName:
    Value: !Ref cfn-PhotoStorageBucket
    Export: { Name: cfn-PhotoAlbum-PhotoBucketName }

  cfn-FrontendWebsiteURL:
    Value: !GetAtt cfn-FrontendBucket.WebsiteURL
    Export: { Name: cfn-PhotoAlbum-FrontendWebsiteURL }
